# Generated by Django 4.1.3 on 2024-03-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='wedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinatesapi.wedding'),
        ),
    ]
