# Generated by Django 4.1.3 on 2024-02-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableguest',
            name='reception_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_tables', to='coordinatesapi.receptiontable'),
        ),
    ]
