# Generated by Django 4.1.3 on 2024-02-25 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupguest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_groups', to='coordinatesapi.group'),
        ),
        migrations.AlterField(
            model_name='groupguest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_guests', to='coordinatesapi.guest'),
        ),
    ]
