# Generated by Django 4.1.3 on 2024-02-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0002_alter_groupguest_group_alter_groupguest_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='first_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_problems', to='coordinatesapi.guest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='second_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_problems', to='coordinatesapi.guest'),
        ),
    ]
