# Generated by Django 4.1.3 on 2024-03-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0002_group_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='coordinatesapi.wedding'),
        ),
    ]
