# Generated by Django 4.1.3 on 2024-02-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0003_alter_problem_first_guest_alter_problem_second_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingplanner',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_planners', to='coordinatesapi.planner'),
        ),
        migrations.AlterField(
            model_name='weddingplanner',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_weddings', to='coordinatesapi.wedding'),
        ),
    ]
