# Generated by Django 4.1.3 on 2024-03-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0003_alter_group_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantguest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_guests', to='coordinatesapi.guest'),
        ),
        migrations.AlterField(
            model_name='participantguest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='coordinatesapi.participant'),
        ),
    ]
