# Generated by Django 4.1.3 on 2024-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0004_alter_participantguest_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
