# Generated by Django 4.1.3 on 2024-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0005_wedding_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
