# Generated by Django 4.1.3 on 2024-02-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0005_alter_couple_first_guest_alter_couple_second_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptiontable',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_tables', to='coordinatesapi.wedding'),
        ),
    ]
