# Generated by Django 4.1.3 on 2024-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0006_alter_wedding_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='coordinatesapi.wedding'),
        ),
    ]
