# Generated by Django 4.1.3 on 2024-03-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0007_alter_participant_wedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='family',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='coordinatesapi.participant'),
        ),
        migrations.AddField(
            model_name='guest',
            name='party',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='primary',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='ParticipantGuest',
        ),
    ]
