# Generated by Django 4.1.3 on 2024-03-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0008_guest_family_guest_participant_guest_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='family',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='coordinatesapi.participant'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
