# Generated by Django 4.1.3 on 2024-03-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0009_alter_guest_family_alter_guest_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='parent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
