# Generated by Django 4.1.3 on 2024-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinatesapi', '0010_guest_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='parent',
            field=models.BooleanField(default=False),
        ),
    ]
